alter table COLLECTION_UPDATE_PERMISSIONS_T drop primary key;
alter table COLLECTION_UPDATE_PERMISSIONS_T drop column ID;

ALTER Table COLLECTION_UPDATE_PERMISSIONS_T ADD ID INTEGER GENERATED ALWAYS AS IDENTITY
 (START WITH 95
 INCREMENT BY 1);
