create table COLLECTION_UPDATE_PERMISSIONS_T
(
    COLLECTION_ID   NUMBER,
    CREATED_DATE    DATE,
    COLLECTION_PATH VARCHAR2(500),
    USER_ID         NUMBER
        constraint METADATA_PERMISSIONS_T_USER_T_ID_FK
            references NCI_DOE_DB_T.USER_T,
    GROUP_ID        NUMBER
        constraint METADATA_PERMISSIONS_T_GROUP_T_ID_FK
            references NCI_DOE_DB_T.GROUP_T,
    ID              NUMBER generated as identity
)	
/

create unique index COLLECTION_UPDATE_PERMISSIONS_T_ID_UINDEX
    on NCI_DOE_DB_T.COLLECTION_UPDATE_PERMISSIONS_T (ID)
/

alter table COLLECTION_UPDATE_PERMISSIONS_T
    add constraint COLLECTION_UPDATE_PERMISSIONS_T_PK
        primary key (ID)
/


GRANT SELECT,INSERT,UPDATE,DELETE ON COLLECTION_UPDATE_PERMISSIONS_T TO MODAC_APP_USER;
